---
- name: install rclone from package
  block:
    - name: detect latest rclone package release
      github_release:
        repository: rclone
        release: "{{ lin_rclone_version }}"
        owner: "{{ lin_rclone_repo_owner }}"
        template: '{download_url}/rclone-{ver}-linux-{goarch}.deb'
        strip_v: false
        version_script: "{{ lin_rclone_binary }} version"
        script_regex: 'v[0-9][.][0-9.a-zA-Z_-]+'
        reinstall: "{{ lin_rclone_upgrade |bool }}"
      tags: skip_ansible_lint
      register: _rclone_release

    - name: install rclone package
      apt:
        deb: "{{ _rclone_release.url }}"
        only_upgrade: "{{ not lin_rclone_upgrade |bool }}"
      register: _rclone_package
      failed_when:
        - _rclone_package.failed
        - _rclone_package.msg is not search('later version is already installed')
      when:
        - _rclone_release is changed
      notify: restart remote systemd mounts
  when: lin_rclone_from_deb |bool

- name: install rclone from zip archive
  block:
    - name: detect latest rclone archive release
      github_release:
        repository: rclone
        release: "{{ lin_rclone_version }}"
        owner: "{{ lin_rclone_repo_owner }}"
        template: '{download_url}/rclone-{ver}-linux-{goarch}.zip'
        strip_v: false
        version_script: "{{ lin_rclone_binary }} version"
        script_regex: 'v[0-9][.][0-9.a-zA-Z_-]+'
        reinstall: "{{ lin_rclone_upgrade |bool }}"
      tags: skip_ansible_lint
      register: _rclone_release

    - name: download and install rclone zip archive
      unarchive:
        remote_src: true
        src: "{{ url }}"
        dest: "{{ lin_rclone_binary |dirname }}"
        extra_opts: '-j'  # junk (flatten) directories
        exclude:
          - "{{ dir }}/rclone.1"
          - "{{ dir }}/README.txt"
          - "{{ dir }}/README.html"
      vars:
        url: "{{ _rclone_release.url }}"
        dir: "{{ url |basename |splitext |first }}"
      register: _rclone_package
      when: _rclone_release is changed
  when: not lin_rclone_from_deb |bool

- name: generate rclone bash completion
  command: "{{ lin_rclone_binary }} genautocomplete bash"
  when: _rclone_package is changed

- name: install fusermount required by automounter
  apt:
    name: fuse
...
