---
- name: run rclone tasks as root
  import_tasks: root.yml
  when: lin_rclone_mounts |d([])
  become: true
  tags: lin_rclone_all

- name: reload systemd mounts now
  meta: flush_handlers
  tags: lin_rclone_all
...
