---
provisioner:
  name: ansible
  inventory:
    group_vars:
      molecule:
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  config_options:
    defaults:
      strategy: linear
      verbosity: 1
  lint:
    name: ansible-lint
verifier:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
    groups:
      - molecule
scenario:
  name: localhost
  test_sequence:
    - lint
    - dependency
    - syntax
    - prepare
    - converge
    - idempotence
    - verify
...
