---
name: test

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      ROLE_NAME: ivansible.lin_rclone
      SCENARIO: ${{ matrix.scenario }}
      ANSIBLE_FORCE_COLOR: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: focal
            os: ubuntu-20.04
            scenario: localhost

          - name: docker
            os: ubuntu-latest
            scenario: default

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: install requisites
        run: |
          sudo apt-get remove -qy python3-yaml
          sudo rm -f /opt/pipx_bin/ansible*
          sudo -H python3 -m pip install -U pip setuptools wheel
          sudo -H pip3 install -r molecule/default/requirements.txt

      - name: run test
        run: |
          molecule test -s $SCENARIO

  galaxy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: push role to galaxy
        uses: 0x022b/galaxy-role-import-action@v1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
...
